services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: booklibrary_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - booklibrary_data:/var/lib/postgresql/data

volumes:
  booklibrary_data: