spring.application.name=booklibrary

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/booklibrary_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG

# API Documentation Configuration
scalar.enabled=true
scalar.path=/docs
scalar.page-title=Book Library API Documentation

# JWT Configuration
jwt.secret=${JWT_SECRET:CfjhS6Xn4kQgzXXCHH/pL3PqZ0hur16e7S6G3RnNnt0=}
jwt.expiration-ms=3600000 