spring.application.name=booklibrary

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/booklibrary_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG

# API Documentation Configuration
scalar.enabled=true
scalar.path=/docs
scalar.page-title=Book Library API Documentation